### ISSUE TITLE
The recent medium article only displays alternative text

### ISSUE THREAD

**Issue by chayansraj** [bxcodec/github-readme-medium-recent-article#19]
Hi,

I hope you are well. 
The medium article plugin only displays alternative text, even after waiting for more than 3 hours. Though, the plugin is really nice. I think something is broken. It is broken on your page also.

**Comment by MaheshBabu11** [comment]
Hi @chayansraj 
Yes , the underlying medium API is not providing the thumbnail URL anymore causing the serverless function to crash

https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@mahesh.babu11 This is the API that is used here to get the RSS data from medium and parse to JSON, in the JSON response the thumbnail var is just an empty string which is the root cause of the issue.

<img width="720" alt="image" src="https://github.com/bxcodec/github-readme-medium-recent-article/assets/43287976/a3341a2e-2d8f-4c6c-8fae-ca8ebd57f901">

**Comment by MaheshBabu11** [comment]
For the time being I have deployed a fix by taking the image from the description instead of the thumbnail. You can use it if u like :

<div name = "medium" align ="left">
  <a target="_blank" href="https://github-readme-medium-recent-article-plugin.vercel.app/medium/@mahesh.babu11/0"><img src="https://github-readme-medium-recent-article-plugin.vercel.app/medium/@mahesh.babu11/0" alt="Recent Article 0">
    
  <a target="_blank" href="https://github-readme-medium-recent-article-plugin.vercel.app/medium/@mahesh.babu11/1"><img src="https://github-readme-medium-recent-article-plugin.vercel.app/medium/@mahesh.babu11/1" alt="Recent Article 1"> 
</div>
